# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63omments.proto\x12\x08\x63omments\"\x94\x02\n\x07\x43omment\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x10\n\x08video_id\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\r\n\x05\x61nger\x18\x06 \x01(\x08\x12\x14\n\x0c\x61nticipation\x18\x07 \x01(\x08\x12\x0f\n\x07\x64isgust\x18\x08 \x01(\x08\x12\x0c\n\x04\x66\x65\x61r\x18\t \x01(\x08\x12\x0b\n\x03joy\x18\n \x01(\x08\x12\x0c\n\x04love\x18\x0b \x01(\x08\x12\x10\n\x08optimism\x18\x0c \x01(\x08\x12\x10\n\x08hopeless\x18\r \x01(\x08\x12\x0f\n\x07sadness\x18\x0e \x01(\x08\x12\x10\n\x08surprise\x18\x0f \x01(\x08\x12\r\n\x05trust\x18\x10 \x01(\x08\"2\n\x0b\x43ommentList\x12#\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x11.comments.Commentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comments_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMMENT']._serialized_start=29
  _globals['_COMMENT']._serialized_end=305
  _globals['_COMMENTLIST']._serialized_start=307
  _globals['_COMMENTLIST']._serialized_end=357
# @@protoc_insertion_point(module_scope)
